//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankaotomasyon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bankaotomasyon.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağış işlemi başarılı. {0} puan, hesabınıza tanımlanmıştır..
        /// </summary>
        internal static string askidaparabasarili {
            get {
                return ResourceManager.GetString("askidaparabasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağış işlemi başarısız..
        /// </summary>
        internal static string askidaparabasarisiz {
            get {
                return ResourceManager.GetString("askidaparabasarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilendirme.
        /// </summary>
        internal static string bilgilendirme {
            get {
                return ResourceManager.GetString("bilgilendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağış.
        /// </summary>
        internal static string btn_Bagis {
            get {
                return ResourceManager.GetString("btn_Bagis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturayı Öde.
        /// </summary>
        internal static string btn_faturaode {
            get {
                return ResourceManager.GetString("btn_faturaode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Askıda Para.
        /// </summary>
        internal static string btn_kAskidaPara {
            get {
                return ResourceManager.GetString("btn_kAskidaPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme.
        /// </summary>
        internal static string btn_odeme {
            get {
                return ResourceManager.GetString("btn_odeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Çekme.
        /// </summary>
        internal static string btn_paracek {
            get {
                return ResourceManager.GetString("btn_paracek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Transferi.
        /// </summary>
        internal static string btn_paratransfer {
            get {
                return ResourceManager.GetString("btn_paratransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Yatırma.
        /// </summary>
        internal static string btn_parayatir {
            get {
                return ResourceManager.GetString("btn_parayatir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puanları Paraya Çevir.
        /// </summary>
        internal static string btn_puancevir {
            get {
                return ResourceManager.GetString("btn_puancevir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şansını Dene.
        /// </summary>
        internal static string btn_sansinidene {
            get {
                return ResourceManager.GetString("btn_sansinidene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string btnGiris {
            get {
                return ResourceManager.GetString("btnGiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan İşlem Geçmişi.
        /// </summary>
        internal static string btnIslemGecmisi {
            get {
                return ResourceManager.GetString("btnIslemGecmisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt.
        /// </summary>
        internal static string btnKayit {
            get {
                return ResourceManager.GetString("btnKayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Kaydı Oluştur.
        /// </summary>
        internal static string btnMusteriKaydiOlustur {
            get {
                return ResourceManager.GetString("btnMusteriKaydiOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili Müşteri Kaydını Sil.
        /// </summary>
        internal static string btnMusteriSil {
            get {
                return ResourceManager.GetString("btnMusteriSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Çek.
        /// </summary>
        internal static string btnParacek {
            get {
                return ResourceManager.GetString("btnParacek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Yatır.
        /// </summary>
        internal static string btnParayatir {
            get {
                return ResourceManager.GetString("btnParayatir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Kodu ile Giriş.
        /// </summary>
        internal static string btnReferans {
            get {
                return ResourceManager.GetString("btnReferans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        internal static string cikis {
            get {
                return ResourceManager.GetString("cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğalgaz.
        /// </summary>
        internal static string Dogalgaz {
            get {
                return ResourceManager.GetString("Dogalgaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektrik.
        /// </summary>
        internal static string Elektrik {
            get {
                return ResourceManager.GetString("Elektrik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura ödeme işlemi başarılı. {0} puan, hesabınıza tanımlanmıştır ve {1} ₺ miktar hesabınıza geri-ödeme olarak eklenmiştir. Bizi tercih ettiğiniz için teşekkür ederiz..
        /// </summary>
        internal static string FaturaBasarili {
            get {
                return ResourceManager.GetString("FaturaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura ödeme işlemi başarısız..
        /// </summary>
        internal static string FaturaBasarisiz {
            get {
                return ResourceManager.GetString("FaturaBasarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Askıda Para.
        /// </summary>
        internal static string FormAskidaPara {
            get {
                return ResourceManager.GetString("FormAskidaPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        internal static string gridAd {
            get {
                return ResourceManager.GetString("gridAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem NO.
        /// </summary>
        internal static string gridislemno {
            get {
                return ResourceManager.GetString("gridislemno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        internal static string gridmiktar {
            get {
                return ResourceManager.GetString("gridmiktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        internal static string gridSoyad {
            get {
                return ResourceManager.GetString("gridSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        internal static string gridtarih {
            get {
                return ResourceManager.GetString("gridtarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan İşlem.
        /// </summary>
        internal static string gridyapilanislem {
            get {
                return ResourceManager.GetString("gridyapilanislem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen referans kodu hatalı..
        /// </summary>
        internal static string hataliref {
            get {
                return ResourceManager.GetString("hataliref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış işlemi iptal edildi..
        /// </summary>
        internal static string iptal {
            get {
                return ResourceManager.GetString("iptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Transferi: {0} {1}.
        /// </summary>
        internal static string islemtabloparatransfer {
            get {
                return ResourceManager.GetString("islemtabloparatransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ekranı.
        /// </summary>
        internal static string KayitEkrani {
            get {
                return ResourceManager.GetString("KayitEkrani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Oluşturma Başarılı..
        /// </summary>
        internal static string KayıtOlusturmaBasarili {
            get {
                return ResourceManager.GetString("KayıtOlusturmaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adı kullanımda. Lütfen başka bir kullanıcı adı seçiniz..
        /// </summary>
        internal static string KullaniciAdiKullanimda {
            get {
                return ResourceManager.GetString("KullaniciAdiKullanimda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekranı.
        /// </summary>
        internal static string KullaniciEkrani {
            get {
                return ResourceManager.GetString("KullaniciEkrani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifre hatalı..
        /// </summary>
        internal static string KullaniciHatali {
            get {
                return ResourceManager.GetString("KullaniciHatali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye:.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puan:.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Askıdaki Toplam Para.
        /// </summary>
        internal static string lbl_AskidakiToplamPara {
            get {
                return ResourceManager.GetString("lbl_AskidakiToplamPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM&apos;deki Toplam Para:.
        /// </summary>
        internal static string lbl_atmtoplampara {
            get {
                return ResourceManager.GetString("lbl_atmtoplampara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çekilecek Tutar.
        /// </summary>
        internal static string lbl_CekilecekTutar {
            get {
                return ResourceManager.GetString("lbl_CekilecekTutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura miktarınızın %5&apos;i Cashback!.
        /// </summary>
        internal static string lbl_faturamesaj {
            get {
                return ResourceManager.GetString("lbl_faturamesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş geldiniz Sayın,.
        /// </summary>
        internal static string lbl_hosgeldiniz {
            get {
                return ResourceManager.GetString("lbl_hosgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir sayı seç ve hemen başla! Oyuna giriş (20) Puan, Ödül (200) Puan!.
        /// </summary>
        internal static string lbl_kAciklama {
            get {
                return ResourceManager.GetString("lbl_kAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenecek Tutar:.
        /// </summary>
        internal static string lbl_odenecektutar {
            get {
                return ResourceManager.GetString("lbl_odenecektutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılacak Bağış Miktarı.
        /// </summary>
        internal static string lbl_YapilacakBagis {
            get {
                return ResourceManager.GetString("lbl_YapilacakBagis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş geldiniz Sayın Yönetici,.
        /// </summary>
        internal static string lblHosgeldinYonetici {
            get {
                return ResourceManager.GetString("lblHosgeldinYonetici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string lblİsim {
            get {
                return ResourceManager.GetString("lblİsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string lblKullaniciAdi {
            get {
                return ResourceManager.GetString("lblKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenecek Faturayı Seçiniz.
        /// </summary>
        internal static string lblOdenecekFaturaText {
            get {
                return ResourceManager.GetString("lblOdenecekFaturaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Kodu.
        /// </summary>
        internal static string lblReferansKodu {
            get {
                return ResourceManager.GetString("lblReferansKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyisim.
        /// </summary>
        internal static string lblSoyisim {
            get {
                return ResourceManager.GetString("lblSoyisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC No.
        /// </summary>
        internal static string lblTC {
            get {
                return ResourceManager.GetString("lblTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Yapılacak Kişi.
        /// </summary>
        internal static string lblTransferYapilacakKisi {
            get {
                return ResourceManager.GetString("lblTransferYapilacakKisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Yapılacak Miktar.
        /// </summary>
        internal static string lblTransferYapilacakMiktar {
            get {
                return ResourceManager.GetString("lblTransferYapilacakMiktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaş.
        /// </summary>
        internal static string lblYas {
            get {
                return ResourceManager.GetString("lblYas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatıralacak Tutar.
        /// </summary>
        internal static string lblYatiralacakTutar {
            get {
                return ResourceManager.GetString("lblYatiralacakTutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Çekme.
        /// </summary>
        internal static string ParaCekme {
            get {
                return ResourceManager.GetString("ParaCekme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para çekme işlemi başarılı..
        /// </summary>
        internal static string ParacekmeBasarili {
            get {
                return ResourceManager.GetString("ParacekmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para çekme işlemi başarısız..
        /// </summary>
        internal static string ParacekmeBasarisiz {
            get {
                return ResourceManager.GetString("ParacekmeBasarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Transfer.
        /// </summary>
        internal static string ParaTransfer {
            get {
                return ResourceManager.GetString("ParaTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para transferi başarılı..
        /// </summary>
        internal static string ParatransferBasarili {
            get {
                return ResourceManager.GetString("ParatransferBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para transferi başarısız..
        /// </summary>
        internal static string ParatransferBasarisiz {
            get {
                return ResourceManager.GetString("ParatransferBasarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Yatırma.
        /// </summary>
        internal static string ParaYatirma {
            get {
                return ResourceManager.GetString("ParaYatirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para yatırma işlemi başarılı..
        /// </summary>
        internal static string ParayatirmaBasarili {
            get {
                return ResourceManager.GetString("ParayatirmaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para yatırma işlemi başarısız..
        /// </summary>
        internal static string ParayatirmaBasarisiz {
            get {
                return ResourceManager.GetString("ParayatirmaBasarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puan çevirme işlemi başarılı..
        /// </summary>
        internal static string puancevirmebasarili {
            get {
                return ResourceManager.GetString("puancevirmebasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puan çevirme işlemi başarısız..
        /// </summary>
        internal static string puancevirmebasarisiz {
            get {
                return ResourceManager.GetString("puancevirmebasarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Kodu ile Giriş.
        /// </summary>
        internal static string ReferansGiris {
            get {
                return ResourceManager.GetString("ReferansGiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şansını Dene.
        /// </summary>
        internal static string SansiniDene {
            get {
                return ResourceManager.GetString("SansiniDene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarısız..
        /// </summary>
        internal static string sansinidenebasarisiz {
            get {
                return ResourceManager.GetString("sansinidenebasarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaybettiniz. Tuttuğunuz sayı: ({0})  Şanslı numara: ({1}).
        /// </summary>
        internal static string sansinidenekaybettiniz {
            get {
                return ResourceManager.GetString("sansinidenekaybettiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tebrikler (200) puan kazandınız. Tuttuğunuz sayı: ({0})  Şanslı numara: ({1}).
        /// </summary>
        internal static string sansinidenekazandiniz {
            get {
                return ResourceManager.GetString("sansinidenekazandiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir sayı seçiniz..
        /// </summary>
        internal static string sansinidenesayisec {
            get {
                return ResourceManager.GetString("sansinidenesayisec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programı kapatmak istiyor musunuz?.
        /// </summary>
        internal static string secim {
            get {
                return ResourceManager.GetString("secim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su.
        /// </summary>
        internal static string Su {
            get {
                return ResourceManager.GetString("Su", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen mail adresi geçersiz..
        /// </summary>
        internal static string yanlismail {
            get {
                return ResourceManager.GetString("yanlismail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan İşlemler.
        /// </summary>
        internal static string Yapilanislemler {
            get {
                return ResourceManager.GetString("Yapilanislemler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Girişi.
        /// </summary>
        internal static string YoneticiGirisi {
            get {
                return ResourceManager.GetString("YoneticiGirisi", resourceCulture);
            }
        }
    }
}
